name: git-push(1)
description: Run git-push(1)
inputs:
  commit-message:
    description: The branch where to push changes.
    required: true
  branch:
    description: The branch where to push changes.
    required: false
    default: ""
  force:
    description: Whether to include -f option.
    required: false
    default: "false"
  user-name:
    description: Git commit user name
    required: false
    default: github-actions
  user-email:
    description: Git commit user email
    required: false
    default: github-actions@github.com
runs:
  using: composite
  steps:
    - name: git-push(1)
      shell: bash -euxo pipefail {0}
      run: |
        changes=$(git status --short | wc -l)
        push_suffix=()
        if [[ "$changes" == "0" ]]; then
          echo "Nothing to change"
          exit 0
        fi

        if [[ '${{ inputs.force }}' == 'true' ]]; then
          push_suffix+=(--force)
        fi

        if [[ -n '${{ inputs.branch }}' ]]; then
          git pull --depth 50 origin '${{ inputs.branch }}'
          git checkout '${{ inputs.branch }}'
          push_suffix+=(--set-upstream origin ${{ inputs.branch }})
        fi

        git config user.name '${{ inputs.user-name }}'
        git config user.email '${{ inputs.user-email }}'
        git add -A
        git commit -m '${{ inputs.commit-message }}'
        git push "${push_suffix[@]}"
